apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.appName }}-route-dev
  labels:
    app: {{ .Values.appName }}
    environment: dev
spec:
  to:
    kind: Service
    name: {{ .Values.appName }}
    weight: 100
  port:
    targetPort: flask
  wildcardPolicy: None
  # Use the value of CUSTOM_HEADER from the config map
  annotations:
    openshift.io/ignore-route-prefix: "true"
    haproxy.router.openshift.io/rewrite-target: /
    haproxy.router.openshift.io/cookie_key: CUSTOM_HEADER
    haproxy.router.openshift.io/cookie_value: {{ .Values.configmap.data.CUSTOM_HEADER }}
