apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-prod
  labels:
    app: {{ .Values.appName }}
    environment: prod
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: flask
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: NodePort
