name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          version=$(echo "$(date +%s)" | awk '{print $1}')
          docker build . --file Dockerfile --tag my-image-name:$version
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DHNAME }}
          password: ${{ secrets.DHPASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DHNAME }}/webapp:$version
      
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Fetch the update the latest image tag
        id: get-latest-tag
        run: |
          repository="eyesoncloud/webapp"
          tags_info=$(curl -s "https://registry.hub.docker.com/v2/repositories/$repository/tags/" | jq -r '.results[] | "\(.name) \(.last_updated)"')
          sorted_tags_info=$(echo "$tags_info" | sort -k2)
          latest_tag_info=$(echo "$sorted_tags_info" | tail -n 1)
          latest_tag=$(echo "$latest_tag_info" | awk '{print $1}')
          sed -i "s|tag:.*|tag: $latest_tag|" helm-webapp/values.yaml
        shell: bash
    
      - name: Commit and push Deployment changes
        run: |
          git config --global user.email "${{ secrets.MAIL }}"
          git config --global user.name "EyesOnCloud"
      
          git add helm-webapp/values.yaml
          git commit -m "Update image tag to $latest_tag"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
